### ISSUE TITLE
Is there a way to buy this product?

### ISSUE THREAD

**Issue by Radek-Suski** [sparkfun/Qwiic_Transparent_OLED_HUD#2]
### Subject of the issue
I really like this product but it seems to be impossible to buy it anywhere

**Comment by nseidle** [comment]
Unfortunately this product has reached end of life. It will be retired shortly.

**Comment by Radek-Suski** [comment]
Hi @nseidle,

Thanks for the reply. 
Is there any replacement model perhaps?

Regards,
Radek
